version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 15672:15672
        - 5672:5672
  api:
    build:
      context: ./projects/server
      dockerfile: Dockerfile
    ports:
        - 3000:3000
    depends_on:
      - rabbitmq